# -*- coding: utf-8 -*-
"""
Worker Agent 的通用响应结构（中文教学注释版）。

这个模块很小，但很关键：它定义了“数据结构的形状”，
也就是 Worker Agent 报告进度时必须遵守的字段格式。

教学要点：
1) 这里用的是 Pydantic 模型，它可以在运行时做数据校验。
2) 同时它又能当成“结构化文档”，让 LLM 知道字段含义。
3) “Schema（模式/结构）”指的是：固定字段 + 类型 + 描述。
"""

from pydantic import BaseModel, Field


# 这是一段很长的说明文字，会作为字段 description 传给 LLM。
# 它告诉模型：总结报告要按怎样的结构来写。
WORKER_PROGRESS_SUMMARY = (
    "## Instruction\n"
    "Review the execution trace above and generate a comprehensive summary "
    "report in Markdown format that addresses the original task/query. "
    "Your report must include:\n\n"
    "1. **Task Overview**\n"
    "   - Include the original query/task verbatim;\n"
    "   - Briefly state the main objective.\n"
    "2. **Comprehensive Analysis**"
    "   - Provide a detailed, structured answer to the original query/task;\n"
    "   - Include all relevant information requested in the original task;\n"
    "   - Support your findings with specific references from your execution "
    "trace;\n"
    "   - Organize content into logical sections with appropriate headings;\n"
    "   - Include data visualizations, tables, or formatted lists when "
    "applicable.\n\n"
    "3. **Completion Checklist**\n"
    "   - Reproduce the original 'Expected Output' checklist of required "
    "tasks/information; **NEVER** makeup additional expected output items "
    "in the checklist\n"
    "   - Mark each item as [x] Completed or [ ] Incomplete;\n"
    "   - For each completed item, reference where in your report this "
    "information appears;\n"
    "   - For incomplete items, explain briefly why they remain unaddressed;\n"
    "4. **Conclusion**\n"
    "   - If the task is fully complete, provide a brief conclusion "
    "summarizing key findings;\n"
    "   - If the task remains incomplete, outline a specific plan to "
    "address remaining items, including:\n"
    "     - Which tools would be used;\n"
    "     - What information is still needed;\n"
    "     - Sequence of planned actions.\n\n"
    "Format your report professionally with consistent heading levels, "
    "proper spacing, and appropriate emphasis for key information."
)


# 另一段说明文字，专门用于“下一步计划”的写法。
# 用多行字符串是为了保留格式。
WORKER_NEXT_STEP_INSTRUCTION = """
If the subtask remains incomplete, outline a specific plan to address remaining
items, including:
     - Which tools would be used
     - What information is still needed
     - Sequence of planned actions
Leave it as an empty string is the subtask has been done successfully.
"""

# “generated_files” 字段的说明：
# 输出必须是字典：文件路径 -> 简短描述。
WORKER_FILE_COLLECTION_INSTRUCTION = (
    "Collect all files generated in the execution process, "
    "such as the files generated by `write_file` and `edit_file`."
    "This field MUST be in dictionary, where"
    "the keys are the paths of generated files "
    "(e.g. '/FULL/PATH/OF/FILE_1.md') and the values are short "
    "descriptions about the generated files."
)


class WorkerResponse(BaseModel):
    """
    Represents the response structure from a worker agent after task execution.

    This class defines the expected format for worker responses, including
    progress summaries, next steps, tool usage information, and task
    completion status.

    Attributes:
        subtask_progress_summary (str):
            Comprehensive summary report of task execution.
        generated_files (dict):
            Dictionary mapping file paths to descriptions of generated files.
        task_done (bool):
            Flag indicating whether the task has been completed.
    """

    # 子任务完成后，Worker 要写的主总结。
    # description 会被展示给 LLM，用来约束输出格式。
    subtask_progress_summary: str = Field(
        default="",
        description=WORKER_PROGRESS_SUMMARY,
    )
    # 任务过程中生成的文件清单。
    # 注意：这里用的是 `default=dict`（类型本身），为了不改变现有行为。
    # 更安全的写法通常是 `default_factory=dict`，但这里暂不改逻辑。
    generated_files: dict = Field(
        default=dict,
        description=WORKER_FILE_COLLECTION_INSTRUCTION,
    )
    # 任务是否完成。编排器会根据这个值决定是否继续分配后续任务。
    task_done: bool = Field(
        default=True,
        description="Whether the task is done or "
        "it requires additional effort",
    )
