# -*- coding: utf-8 -*-
# pylint: disable=C2801, W0611, W0212
from typing import Optional, Any, Callable
from functools import partial

from agentscope.model import ChatModelBase
from agentscope.formatter import FormatterBase
from agentscope.memory import MemoryBase
from dotenv import load_dotenv

from alias.agent.agents import AliasAgentBase
from alias.agent.tools import AliasToolkit
from alias.agent.utils.constants import WORKER_MAX_ITER
from alias.agent.agents.common_agent_utils import (
    WorkerResponse,
)

load_dotenv()


class ReActWorker(AliasAgentBase):
    def __init__(
        self,
        name: str,
        model: ChatModelBase,
        formatter: FormatterBase,
        memory: MemoryBase,
        toolkit: AliasToolkit,
        sys_prompt: Optional[str] = None,
        max_iters: int = 10,
        state_saving_dir: Optional[str] = None,
        session_service: Any = None,
    ) -> None:
        """Initialize the ReAct agent with the given name, model config name
        and tools.
        """
        super().__init__(
            name=name,
            sys_prompt=sys_prompt,
            model=model,
            formatter=formatter,
            memory=memory,
            toolkit=toolkit,
            max_iters=max_iters,
            session_service=session_service,
            state_saving_dir=state_saving_dir,
        )

        self._required_structured_model = WorkerResponse
        self.reply: Callable = partial(
            self.reply,
            structured_model=self._required_structured_model,
        )

        self.max_iters: int = max(self.max_iters, WORKER_MAX_ITER)

    def generate_response(
        self,
        **kwargs,
    ):  # pylint: disable=useless-parent-delegation
        """
        Generate a response summarizing the execution progress of the
        given subtask.
        Args:
            task_done (bool):
                REQUIRED! Whether the subtask was done or not.
            subtask_progress_summary (str):
                REQUIRED! The subtask progress summary.
            generated_files (dict[str, str]):
                REQUIRED! Collect all files generated in the execution process,
                such as the files generated by `write_file` and `edit_file`.
                This field MUST be in dictionary, where the keys are the
                paths of generated files (e.g. '/FULL/PATH/OF/FILE_1.md') and
                the values are short descriptions about the generated files.
        """
        return super().generate_response(**kwargs)
